### ISSUE TITLE
Been Looking For This

### ISSUE THREAD

**Issue by mikecann** [Asana/typescript-namespace-imports-vscode-plugin#5]
I have been looking for this extension for a while, its exactly what I want but for some reason I cant get it to work... I

![image](https://user-images.githubusercontent.com/215033/66884886-1e938d80-f005-11e9-8f9d-bffcf9baafce.png)

Any ideas?

**Comment by Josh211ua** [comment]
Sorry for the delay Mike, I think I didn't have my notifications set up correctly to see this issue. I wonder if the problem here is related to your tsconfig.json files. The extension looks for a tsconfig.json for the current file by looking in the current directory up to the root of the project. It uses the settings in the file to determine which other files should be offered as imports. Maybe adding a tsconfig.json file inside features or at the root of your project would fix this issue.

**Comment by mikecann** [comment]
oh I totally forgot about this issue too :P

I went ahead and tried to create a version of this myself: https://github.com/mikecann/ts-namespace-imports but I ran into performance issues so abandoned it :(
